name: Delete from S3

on: delete

jobs:
  deploy:
    name: delete
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Delete review environment from S3
        run: |
          BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
          aws s3 rm s3://github-approval-artifacts/${BRANCH} --recursive
