name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'   
      - run: echo "npmRegistries:" >> .yarnrc.yml
      - run: echo '  - "https://npm.pkg.github.com"' >> .yarnrc.yml
      - run: echo '      npmAuthToken:${{secrets.GITHUB_TOKEN}}' >> .yarnrc.yml
      - run: echo '      npmAlwaysAuth:true' >> .yarnrc.yml
      - run: echo 'npmScopes:' >> .yarnrc.yml
      - run: echo '  - psu-ooe:' >> .yarnrc.yml
      - run: echo '      npmAlwaysAuth:true' >> .yarnrc.yml
      - run: echo '      npmRegistryServer:"https://npm.pkg.github.com"' >> .yarnrc.yml
      - run: cat .yarnrc.yml
      - run: yarn install
      - run: yarn workspaces foreach install
      - run: npm run build
      - run: yarn workspaces foreach npm publish --tolerate-republish
