name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'   
      - run: echo "npmRegistries:" >> .yarnrc
      - run: echo '  \"https://npm.pkg.github.com\":' >> .yarnrc
      - run: echo '    npmAuthToken: @{{secrets.GITHUB_TOKEN}}' >> .yarnrc
      - run: echo '    npmAlwaysAuth: true' >> .yarnrc
      - run: echo 'npmScopes:' >> .yarnrc
      - run: echo '  psu-ooe:' >> .yarnrc
      - run: echo '    npmAlwaysAuth: true' >> .yarnrc
      - run: echo '    npmRegistryServer: "https://npm.pkg.github.com"' >> .yarnrc
      - run: cat .yarnrc
#      - run: yarn install
#      - run: yarn workspaces foreach install
#      - run: npm run build
#      - run: yarn workspaces foreach npm publish --tolerate-republish
