name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm i -g corepack
      - run: corepack enable
      - run: yarn init -2
      - run: yarn plugin import workspace-tools
      - run: yarn workspaces foreach install
      - run: yarn workspaces foreach npm publish --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
